// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package main

import (
	"context"
)

type Querier interface {
	AddContainer(ctx context.Context, arg AddContainerParams) error
	AddContainerAddr(ctx context.Context, arg AddContainerAddrParams) error
	AddContainerAlias(ctx context.Context, arg AddContainerAliasParams) error
	DeleteContainer(ctx context.Context, id string) error
	GetContainers(ctx context.Context) ([]Container, error)
}

var _ Querier = (*Queries)(nil)
